Included closeToTime in asserts and tdd aliases. Before it was missing and could not be called via chai, returning error "Uncaught TypeError: assert.closeToTime is not a function".